redis:
  prefix: hub
  jobPoolSize: 10
  nodes:
    - sequence: 1
      host: "127.0.0.1"
      port: 6379
server:
  address: "0.0.0.0"
  port: 4774
  enable: true
  maxHeaderListSize: 1048576
client:
  enable: true
metrics:
  address: "0.0.0.0"
  port: 9090
  routes:
    metrics: /metrics
    readiness: /ready
    liveness: /health
protos:
  services:
    - service: mock.v1.MockedUnaryService
      consumer:
        concurrency: 200
        block: "5000ms"
        retry:
          limit: 3
          pageSize: 1000
          deadline: "10000ms"
      client:
        address: "127.0.0.1"
        port: 4775
      methods:
        - name: SendUnaryMock
          pattern: queue
          capped: 500
          stream: SendUnaryMock
    - service: mock.v1.MockedClientStreamService
      consumer:
        concurrency: 100
        block: "5000ms"
        retry:
          limit: 3
          pageSize: 1000
          deadline: "10000ms"
      client:
        address: "127.0.0.1"
        port: 4775
      methods:
        - name: SendClientStreamMock
          pattern: fireAndForget
          capped: 500
          stream: SendClientStreamMock
          timeoutWaitForNext: "1s"