redis:
  prefix: hub
  jobPoolSize: 3
  nodes:
    - sequence: 1
      host: "127.0.0.1"
      port: 6379
    # - sequence: 2
    #   host: "127.0.0.1"
    #   port: 6479
server:
  address: "0.0.0.0"
  port: 4774
  enable: true
  maxHeaderListSize: 1048576
client:
  enable: true
metrics:
  address: "0.0.0.0"
  port: 9090
  routes:
    metrics: /metrics
    readiness: /ready
    liveness: /health
protos:
  services:
    - service: mock.v1.MockedUnaryService
      consumer:
        concurrency: 50
        block: "5000ms"
        retry:
          limit: 3
          pageSize: 1000
          deadline: "10000ms"
      client:
        address: "127.0.0.1"
        port: 4775
        healthcheck:
          maxRetryTime: 30000
          retries: 5
          randomize: true
          minTimeout: 2000
      methods:
        - name: SendUnaryMock
          pattern: queue
          capped: 100
          stream: SendUnaryMock
          deadline: 15000
          expiresIn: 40000
          dropRequest: true