// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job-event.proto

package polygate_data

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobEvent_Status int32

const (
	JobEvent_RESOLVED JobEvent_Status = 0
	JobEvent_REJECTED JobEvent_Status = 1
	JobEvent_AWAITING JobEvent_Status = 2
	JobEvent_FIRED    JobEvent_Status = 3
)

var JobEvent_Status_name = map[int32]string{
	0: "RESOLVED",
	1: "REJECTED",
	2: "AWAITING",
	3: "FIRED",
}

var JobEvent_Status_value = map[string]int32{
	"RESOLVED": 0,
	"REJECTED": 1,
	"AWAITING": 2,
	"FIRED":    3,
}

func (x JobEvent_Status) String() string {
	return proto.EnumName(JobEvent_Status_name, int32(x))
}

func (JobEvent_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69100c2d0af942b0, []int{2, 0}
}

type MetadataItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataItem) Reset()         { *m = MetadataItem{} }
func (m *MetadataItem) String() string { return proto.CompactTextString(m) }
func (*MetadataItem) ProtoMessage()    {}
func (*MetadataItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_69100c2d0af942b0, []int{0}
}

func (m *MetadataItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataItem.Unmarshal(m, b)
}
func (m *MetadataItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataItem.Marshal(b, m, deterministic)
}
func (m *MetadataItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataItem.Merge(m, src)
}
func (m *MetadataItem) XXX_Size() int {
	return xxx_messageInfo_MetadataItem.Size(m)
}
func (m *MetadataItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataItem.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataItem proto.InternalMessageInfo

func (m *MetadataItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MetadataItem) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type JobError struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobError) Reset()         { *m = JobError{} }
func (m *JobError) String() string { return proto.CompactTextString(m) }
func (*JobError) ProtoMessage()    {}
func (*JobError) Descriptor() ([]byte, []int) {
	return fileDescriptor_69100c2d0af942b0, []int{1}
}

func (m *JobError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobError.Unmarshal(m, b)
}
func (m *JobError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobError.Marshal(b, m, deterministic)
}
func (m *JobError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobError.Merge(m, src)
}
func (m *JobError) XXX_Size() int {
	return xxx_messageInfo_JobError.Size(m)
}
func (m *JobError) XXX_DiscardUnknown() {
	xxx_messageInfo_JobError.DiscardUnknown(m)
}

var xxx_messageInfo_JobError proto.InternalMessageInfo

func (m *JobError) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *JobError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type JobEvent struct {
	Payload              []byte          `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Id                   string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Method               string          `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Service              string          `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Status               JobEvent_Status `protobuf:"varint,5,opt,name=status,proto3,enum=polygate.data.JobEvent_Status" json:"status,omitempty"`
	ConsumerId           string          `protobuf:"bytes,6,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Group                string          `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	Stream               string          `protobuf:"bytes,8,opt,name=stream,proto3" json:"stream,omitempty"`
	StreamId             string          `protobuf:"bytes,9,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ProducerId           string          `protobuf:"bytes,10,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Metadata             []*MetadataItem `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty"`
	Error                *JobError       `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JobEvent) Reset()         { *m = JobEvent{} }
func (m *JobEvent) String() string { return proto.CompactTextString(m) }
func (*JobEvent) ProtoMessage()    {}
func (*JobEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_69100c2d0af942b0, []int{2}
}

func (m *JobEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobEvent.Unmarshal(m, b)
}
func (m *JobEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobEvent.Marshal(b, m, deterministic)
}
func (m *JobEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobEvent.Merge(m, src)
}
func (m *JobEvent) XXX_Size() int {
	return xxx_messageInfo_JobEvent.Size(m)
}
func (m *JobEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_JobEvent.DiscardUnknown(m)
}

var xxx_messageInfo_JobEvent proto.InternalMessageInfo

func (m *JobEvent) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *JobEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobEvent) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *JobEvent) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *JobEvent) GetStatus() JobEvent_Status {
	if m != nil {
		return m.Status
	}
	return JobEvent_RESOLVED
}

func (m *JobEvent) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *JobEvent) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *JobEvent) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *JobEvent) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *JobEvent) GetProducerId() string {
	if m != nil {
		return m.ProducerId
	}
	return ""
}

func (m *JobEvent) GetMetadata() []*MetadataItem {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *JobEvent) GetError() *JobError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("polygate.data.JobEvent_Status", JobEvent_Status_name, JobEvent_Status_value)
	proto.RegisterType((*MetadataItem)(nil), "polygate.data.MetadataItem")
	proto.RegisterType((*JobError)(nil), "polygate.data.JobError")
	proto.RegisterType((*JobEvent)(nil), "polygate.data.JobEvent")
}

func init() { proto.RegisterFile("job-event.proto", fileDescriptor_69100c2d0af942b0) }

var fileDescriptor_69100c2d0af942b0 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x49, 0xd2, 0x4d, 0x93, 0xd9, 0x6d, 0x89, 0x2c, 0x04, 0x96, 0x2a, 0x41, 0x94, 0x53,
	0x2e, 0xcd, 0x61, 0x91, 0xa0, 0x17, 0x0e, 0x15, 0x1b, 0x50, 0x2a, 0xfe, 0x48, 0x6e, 0x05, 0x47,
	0xe4, 0x8d, 0x47, 0x4b, 0x60, 0x53, 0x47, 0xb6, 0xb3, 0xd2, 0xbe, 0x26, 0x4f, 0x84, 0x6c, 0x27,
	0x08, 0x50, 0x6f, 0xf3, 0x1b, 0x7f, 0x33, 0xf3, 0x4d, 0x26, 0xf0, 0xf8, 0x87, 0xdc, 0x5e, 0xe2,
	0x01, 0xef, 0x4d, 0x35, 0x28, 0x69, 0x24, 0x39, 0x1b, 0xe4, 0xfe, 0xb8, 0xe3, 0x06, 0x2b, 0xc1,
	0x0d, 0x2f, 0xae, 0x60, 0xf5, 0x11, 0x0d, 0xb7, 0x71, 0x63, 0xb0, 0x27, 0x19, 0x44, 0x3f, 0xf1,
	0x48, 0x83, 0x3c, 0x28, 0x53, 0x66, 0x43, 0xf2, 0x14, 0xe2, 0x03, 0xdf, 0x8f, 0xa8, 0x69, 0x98,
	0x47, 0x65, 0xca, 0x26, 0x2a, 0xae, 0x20, 0xb9, 0x91, 0xdb, 0x5a, 0x29, 0xa9, 0x08, 0x81, 0x93,
	0x56, 0x0a, 0x74, 0x65, 0x67, 0xcc, 0xc5, 0x84, 0xc2, 0x69, 0x8f, 0x5a, 0xf3, 0x1d, 0xd2, 0xd0,
	0x75, 0x9b, 0xb1, 0xf8, 0x15, 0xf9, 0x52, 0xeb, 0xca, 0xca, 0x06, 0x7e, 0xdc, 0x4b, 0x2e, 0x5c,
	0xf5, 0x8a, 0xcd, 0x48, 0xce, 0x21, 0xec, 0xc4, 0x54, 0x1b, 0x76, 0xc2, 0x1a, 0xe9, 0xd1, 0x7c,
	0x97, 0x82, 0x46, 0x2e, 0x37, 0x91, 0xed, 0xa0, 0x51, 0x1d, 0xba, 0x16, 0xe9, 0x89, 0x1f, 0x34,
	0x21, 0x79, 0x05, 0xb1, 0x36, 0xdc, 0x8c, 0x9a, 0x2e, 0xf2, 0xa0, 0x3c, 0x5f, 0x3f, 0xaf, 0xfe,
	0x59, 0xbe, 0x9a, 0x4d, 0x54, 0xb7, 0x4e, 0xc5, 0x26, 0x35, 0x79, 0x01, 0xcb, 0x56, 0xde, 0xeb,
	0xb1, 0x47, 0xf5, 0xad, 0x13, 0x34, 0x76, 0x5d, 0x61, 0x4e, 0x35, 0x82, 0x3c, 0x81, 0xc5, 0x4e,
	0xc9, 0x71, 0xa0, 0xa7, 0xee, 0xc9, 0x83, 0x35, 0xa8, 0x8d, 0x42, 0xde, 0xd3, 0xc4, 0x1b, 0xf4,
	0x44, 0x2e, 0x20, 0xf5, 0x91, 0x6d, 0x96, 0xba, 0xa7, 0xc4, 0x27, 0x1a, 0x61, 0x67, 0x0d, 0x4a,
	0x8a, 0xb1, 0xf5, 0xb3, 0xc0, 0xcf, 0x9a, 0x53, 0x8d, 0x20, 0xaf, 0x21, 0xe9, 0xa7, 0x0b, 0xd1,
	0x65, 0x1e, 0x95, 0xcb, 0xf5, 0xc5, 0x7f, 0x6b, 0xfc, 0x7d, 0x40, 0xf6, 0x47, 0x4c, 0x2e, 0x61,
	0x81, 0xf6, 0x3a, 0x74, 0x95, 0x07, 0xe5, 0x72, 0xfd, 0xec, 0x81, 0xe5, 0xed, 0x33, 0xf3, 0xaa,
	0xe2, 0x0d, 0xc4, 0xfe, 0x33, 0x90, 0x15, 0x24, 0xac, 0xbe, 0xfd, 0xfc, 0xe1, 0x4b, 0xbd, 0xc9,
	0x1e, 0x79, 0xba, 0xa9, 0xdf, 0xde, 0xd5, 0x9b, 0x2c, 0xb0, 0x74, 0xfd, 0xf5, 0xba, 0xb9, 0x6b,
	0x3e, 0xbd, 0xcf, 0x42, 0x92, 0xc2, 0xe2, 0x5d, 0xc3, 0xea, 0x4d, 0x16, 0x6d, 0x63, 0xf7, 0x7b,
	0xbd, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xb6, 0x08, 0x16, 0x71, 0x02, 0x00, 0x00,
}
